name: task_manager
description: This App is for Task management

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo.png

  
  fonts:
    - family: varela
      fonts:
        - asset: assets/fonts/varela.ttf
  
  
  
  
  
  
  
  
  
  
